import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(resolve(ROOT, "packages/frontend/verifier/package.json"));
const Ajv2020 = require("ajv/dist/2020").default;
const standaloneCode = require("ajv/dist/standalone").default;
const addFormats = require("ajv-formats").default;
const SCHEMA_DIRECTORY = resolve(ROOT, "documentation/schemas");
const OUTPUT = resolve(
  ROOT,
  "packages/frontend/verifier/src/generated/schema-validators.ts",
);
const SCHEMA_NAMES = [
  "attestation.v1.schema.json",
  "attestation.v2.schema.json",
  "attestation.v3.schema.json",
  "bundle-manifest.v1.schema.json",
  "bundle-manifest.v2.schema.json",
  "bundle-manifest.v3.schema.json",
  "common.v1.schema.json",
  "jws-protected-header.v1.schema.json",
  "jws-protected-header.v2.schema.json",
  "jws-protected-header.v3.schema.json",
  "key-distrust-event.v1.schema.json",
  "lifecycle-event.v1.schema.json",
  "operational-key-statement.v1.schema.json",
  "package-manifest.v1.schema.json",
  "review-completion.v1.schema.json",
  "status-snapshot.v1.schema.json",
  "timestamp-evidence.v1.schema.json",
  "trust-store.v1.schema.json",
  "verification-result.v1.schema.json",
];

const ajv = new Ajv2020({
  code: { esm: true, source: true },
  strict: true,
});
addFormats(ajv);

const schemaSources = {};
const validatorExports = {};
for (const [index, name] of SCHEMA_NAMES.entries()) {
  const source = await readFile(resolve(SCHEMA_DIRECTORY, name), "utf8");
  const schema = JSON.parse(source);
  ajv.addSchema(schema, name);
  schemaSources[name] = source;
  validatorExports[`validateSchema${index}`] = name;
}

const runtimeImports = new Set();
let generated = standaloneCode(ajv, validatorExports);
generated = generated.replace(
  /const (\w+) = require\("ajv\/dist\/runtime\/(ucs2length|equal)"\)\.default;/g,
  (_, identifier, helper) => {
    runtimeImports.add(`import ${identifier} from "ajv/dist/runtime/${helper}.js";`);
    return "";
  },
);
generated = generated.replace(
  /const (\w+) = require\("ajv-formats\/dist\/formats"\)\.fullFormats\["date-time"\];/g,
  (_, identifier) => {
    runtimeImports.add(
      `import { fullFormats as ajvFullFormats } from "ajv-formats/dist/formats.js";`,
    );
    return `const ${identifier} = ajvFullFormats["date-time"];`;
  },
);
if (generated.includes("require(")) {
  throw new Error("standalone validators contain an unexpected runtime require");
}
const validators = SCHEMA_NAMES.map(
  (name, index) => `  ${JSON.stringify(name)}: validateSchema${index},`,
).join("\n");
const output =
  `// Generated by scripts/build_verifier_schemas.mjs. Do not edit.\n` +
  `// @ts-nocheck\n` +
  `${[...runtimeImports].join("\n")}\n` +
  `${generated}\n` +
  `export const schemaValidators = Object.freeze({\n${validators}\n});\n` +
  `export const canonicalSchemaSources = Object.freeze(${JSON.stringify(schemaSources)});\n`;

await mkdir(dirname(OUTPUT), { recursive: true });
let previous = "";
try {
  previous = await readFile(OUTPUT, "utf8");
} catch (error) {
  if (error?.code !== "ENOENT") {
    throw error;
  }
}
if (previous !== output) {
  await writeFile(OUTPUT, output, "utf8");
}
