import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const trustPath = process.env.OFFLINE_VERIFIER_TRUST_STORE;
if (!trustPath) {
  throw new Error("OFFLINE_VERIFIER_TRUST_STORE is required");
}
const version = process.env.OFFLINE_VERIFIER_VERSION ?? "0.1.0";
if (!/^[0-9]+\.[0-9]+\.[0-9]+$/u.test(version)) {
  throw new Error("OFFLINE_VERIFIER_VERSION must be a semantic version");
}
const trustBytes = await readFile(resolve(trustPath));
let trust;
try {
  trust = JSON.parse(trustBytes.toString("utf8"));
} catch {
  throw new Error("OFFLINE_VERIFIER_TRUST_STORE must contain JSON");
}
if (typeof trust !== "object" || trust === null || Array.isArray(trust)) {
  throw new Error("OFFLINE_VERIFIER_TRUST_STORE must contain an object");
}
for (const rootRecord of trust.reviewedproof_roots ?? []) {
  if (rootRecord?.jwk && Object.hasOwn(rootRecord.jwk, "d")) {
    throw new Error("OFFLINE_VERIFIER_TRUST_STORE must contain public keys only");
  }
}
const output = resolve(root, "apps/offline-verifier/src/generated/release-inputs.ts");
const source =
  "// Generated by scripts/prepare_browser_inputs.mjs. Do not edit.\n" +
  `export const VERIFIER_VERSION: string = ${JSON.stringify(version)};\n` +
  "export const TRUST_STORE_BYTES: Uint8Array = new TextEncoder().encode(\n" +
  `  ${JSON.stringify(trustBytes.toString("utf8"))},\n` +
  ");\n";
await mkdir(dirname(output), { recursive: true });
await writeFile(output, source, "utf8");
